// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1t_CAM5n56PmKLdkM869UfMrCavyWYl0',
    appId: '1:926360910600:web:5cc949beab327e33ac4abd',
    messagingSenderId: '926360910600',
    projectId: 'flutproj-4f29d',
    authDomain: 'flutproj-4f29d.firebaseapp.com',
    storageBucket: 'flutproj-4f29d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2GxmiuNDjCm6PnuIQfqFfamon9O2soW4',
    appId: '1:926360910600:android:6c97d28e1dea7637ac4abd',
    messagingSenderId: '926360910600',
    projectId: 'flutproj-4f29d',
    storageBucket: 'flutproj-4f29d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXULWzlVSrdJIvZr1dtA9K0ze0mX5Ljzk',
    appId: '1:926360910600:ios:faddf6aa59ea3956ac4abd',
    messagingSenderId: '926360910600',
    projectId: 'flutproj-4f29d',
    storageBucket: 'flutproj-4f29d.appspot.com',
    iosBundleId: 'com.example.httpproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXULWzlVSrdJIvZr1dtA9K0ze0mX5Ljzk',
    appId: '1:926360910600:ios:6ba53d86183a7fe4ac4abd',
    messagingSenderId: '926360910600',
    projectId: 'flutproj-4f29d',
    storageBucket: 'flutproj-4f29d.appspot.com',
    iosBundleId: 'com.example.httpproj.RunnerTests',
  );
}
