// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnWlOxKdkTZw1DM32Ukd2oe4QwurinDD4',
    appId: '1:519297961450:web:430a51ac77e4be54b67693',
    messagingSenderId: '519297961450',
    projectId: 'pushnotification-d1409',
    authDomain: 'pushnotification-d1409.firebaseapp.com',
    storageBucket: 'pushnotification-d1409.appspot.com',
    measurementId: 'G-P0KJDT7Y2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANKaWyuCAjAaspNHvwsfFjPnYoOHxRZsk',
    appId: '1:519297961450:android:587b6e6ef122a0d7b67693',
    messagingSenderId: '519297961450',
    projectId: 'pushnotification-d1409',
    storageBucket: 'pushnotification-d1409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD00F6Uaq9tAJNPBxU32VtIOD1V8hnNEm8',
    appId: '1:519297961450:ios:7d9b7e3b6bcf9cc0b67693',
    messagingSenderId: '519297961450',
    projectId: 'pushnotification-d1409',
    storageBucket: 'pushnotification-d1409.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD00F6Uaq9tAJNPBxU32VtIOD1V8hnNEm8',
    appId: '1:519297961450:ios:eff91d6151f184f2b67693',
    messagingSenderId: '519297961450',
    projectId: 'pushnotification-d1409',
    storageBucket: 'pushnotification-d1409.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
